image: node:12.14.1
pipelines:
  default:
    - parallel:
        - step:
            name: Unit Test Back-end
            script:
              - cd api
              - npm install
              - npm run test
        - step:
            name: Unit Test Front-end 
            script:
              - cd frontend
              - npm install
              - npm run lint
              - npm run test
  branches:
    master:
      - parallel:
          - step:
              name: Unit Test Back-end
              script:
                - cd api
                - npm install
                - npm run test
                - npm run test:e2e
          - step:
              name: Unit Test Front-end 
              script:
                - cd frontend
                - npm install
                - npm run lint
                - npm run test 
          