export const GET_DEVIATIONS = 'GET_DEVIATIONS';
export const GET_DEVIATIONS_SUCCESS = 'GET_DEVIATIONS_SUCCESS';
export const GET_DEVIATIONS_FAILURE = 'GET_DEVIATIONS_FAILURE';

export const GET_DEVIATION = 'GET_DEVIATION';
export const GET_DEVIATION_SUCCESS = 'GET_DEVIATION_SUCCESS';
export const GET_DEVIATION_FAILURE = 'GET_DEVIATION_FAILURE';

export const CREATE_DEVIATION_IMAGE = 'CREATE_DEVIATION_IMAGE';
export const CREATE_DEVIATION_IMAGE_SUCCESS = 'CREATE_DEVIATION_IMAGE_SUCCESS';
export const CREATE_DEVIATION_IMAGE_FAILURE = 'CREATE_DEVIATION_IMAGE_FAILURE';


export const UPDATE_DEVIATION = 'UPDATE_DEVIATION';
export const UPDATE_DEVIATION_SUCCESS = 'UPDATE_DEVIATION_SUCCESS';
export const UPDATE_DEVIATION_FAILURE = 'UPDATE_DEVIATION_FAILURE';


export const GET_IMAGE = 'GET_IMAGE';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAILURE = 'GET_IMAGE_FAILURE';
