export enum ConfirmSetStatusEnum{
    COMPANY_FILLING = 'COMPANY_FILLING',
    CONFIRMING = 'CONFIRMING',
    IN_DEVIATION_FIXING = 'IN_DEVIATION_FIXING',
    IN_DEVIATION_PROCESSING = 'IN_DEVIATION_PROCESSING',
    IN_AUDIT = 'IN_AUDIT',
    COMPLETED = 'COMPLETED',
}

export enum ConfirmSetCreateStatusEnum {
    COMPANY_FILLING = 'COMPANY_FILLING',
    COMPLETED = 'COMPLETED',
}

export enum ConfirmSetReviewStatusEnum {
    COMPANY_FILLING = 'COMPANY_FILLING',
    COMPLETED = 'COMPLETED',
    IN_AUDIT = 'IN_AUDIT',
}