export const GET_SEGMENT = 'GET_SEGMENT';
export const GET_SEGMENT_SUCCESS = 'GET_SEGMENT_SUCCESS';
export const GET_SEGMENT_FAILURE = 'GET_SEGMENT_FAILURE';

export const SELECT_SEGMENT = 'SELECT_SEGMENT';
export const SELECT_SEGMENT_SUCCESS = 'SELECT_SEGMENT_SUCCESS';
export const SELECT_SEGMENT_FAILURE = 'SELECT_SEGMENT_FAILURE';