
export const CREATE_CONFIRMSET = 'CREATE_CONFIRMSET';
export const CREATE_CONFIRMSET_SUCCESS = 'CREATE_CONFIRMSET_SUCCESS';
export const CREATE_CONFIRMSET_FAILURE = 'CREATE_CONFIRMSET_FAILURE';

export const CREATE_CONFIRMSET_SEGMENT = 'CREATE_CONFIRMSET_SEGMENT';
export const CREATE_CONFIRMSET_SEGMENT_SUCCESS = 'CREATE_CONFIRMSET_SEGMENT_SUCCESS';
export const CREATE_CONFIRMSET_SEGMENT_FAILURE = 'CREATE_CONFIRMSET_SEGMENT_FAILURE';


export const CREATE_CONFIRMSET_CONTACT = 'CREATE_CONFIRMSET_CONTACT';
export const CREATE_CONFIRMSET_CONTACT_SUCCESS = 'CREATE_CONFIRMSET_CONTACT_SUCCESS';
export const CREATE_CONFIRMSET_CONTACT_FAILURE = 'CREATE_CONFIRMSET_CONTACT_FAILURE';

export const CREATE_CONFIRMSET_CERTIFICATE = 'CREATE_CONFIRMSET_CERTIFICATE';
export const CREATE_CONFIRMSET_CERTIFICATE_SUCCESS = 'CREATE_CONFIRMSET_CERTIFICATE_SUCCESS';
export const CREATE_CONFIRMSET_CERTIFICATE_FAILURE = 'CREATE_CONFIRMSET_CERTIFICATE_FAILURE';

export const GET_CONFIRMSET = 'GET_CONFIRMSET';
export const GET_CONFIRMSET_SUCCESS = 'GET_CONFIRMSET_SUCCESS';
export const GET_CONFIRMSET_FAILURE = 'GET_CONFIRMSET_FAILURE';

export const GET_CONFIRMSETS_BY_ID = 'GET_CONFIRMSETS_BY_ID';
export const GET_CONFIRMSETS_BY_ID_SUCCESS = 'GET_CONFIRMSETS_BY_ID_SUCCESS';
export const GET_CONFIRMSETS_BY_ID_FAILURE = 'GET_CONFIRMSETS_BY_ID_FAILURE';

export const UPDATE_CONFIRMSET = 'UPDATE_CONFIRMSET';
export const UPDATE_CONFIRMSET_SUCCESS = 'UPDATE_CONFIRMSET_SUCCESS';
export const UPDATE_CONFIRMSET_FAILURE = 'UPDATE_CONFIRMSET_FAILURE';

export const UPDATE_CONFIRMSET_CERTIFICATES = 'UPDATE_CONFIRMSET_CERTIFICATES';
export const UPDATE_CONFIRMSET_CERTIFICATES_SUCCESS = 'UPDATE_CONFIRMSET_CERTIFICATES_SUCCESS';
export const UPDATE_CONFIRMSET_CERTIFICATES_FAILURE = 'UPDATE_CONFIRMSET_CERTIFICATES_FAILURE';

export const UPDATE_CONFIRMSET_SEGMENT = 'UPDATE_CONFIRMSET_SEGMENT';
export const UPDATE_CONFIRMSET_SEGMENT_SUCCESS = 'UPDATE_CONFIRMSET_SEGMENT_SUCCESS';
export const UPDATE_CONFIRMSET_SEGMENT_FAILURE = 'UPDATE_CONFIRMSET_SEGMENT_FAILURE';

export const UPDATE_CONFIRMSET_SEGMENT_ITEM = 'UPDATE_CONFIRMSET_SEGMENT_ITEM';
export const UPDATE_CONFIRMSET_SEGMENT_ITEM_SUCCESS = 'UPDATE_CONFIRMSET_SEGMENT_ITEM_SUCCESS';
export const UPDATE_CONFIRMSET_SEGMENT_ITEM_FAILURE = 'UPDATE_CONFIRMSET_SEGMENT_ITEM_FAILURE';

export const CONFIRMSETS_LISTING = 'CONFIRMSETS_LISTING';
export const CONFIRMSETS_LISTING_SUCCESS = 'CONFIRMSETS_LISTING_SUCCESS';
export const CONFIRMSETS_LISTING_FAILURE = 'CONFIRMSETS_LISTING_FAILURE';

export const CONFIRMSETS_FILTERED_LIST = 'CONFIRMSETS_FILTERED_LIST';
export const CONFIRMSETS_FILTERED_LIST_SUCCESS = 'CONFIRMSETS_FILTERED_LIST_SUCCESS';
export const CONFIRMSETS_FILTERED_LIST_FAILURE = 'CONFIRMSETS_FILTERED_LIST_FAILURE';
export const CONFIRMSETS_FILTERED_LIST_PAGINATION = 'CONFIRMSETS_FILTERED_LIST_PAGINATION';

export const CONFIRMSET_DROPDOWNVALUE = 'CONFIRMSET_DROPDOWNVALUE';

export const GET_CONFIRMSET_CERTIFICATES = 'GET_CONFIRMSET_CERTIFICATES';
export const GET_CONFIRMSET_CERTIFICATES_SUCCESS = 'GET_CONFIRMSET_CERTIFICATES_SUCCESS';
export const GET_CONFIRMSET_CERTIFICATES_FAILURE = 'GET_CONFIRMSET_CERTIFICATES_FAILURE';

export const DELETE_CONFIRMSET_CONTACT = 'DELETE_CONFIRMSET_CONTACT';
export const DELETE_CONFIRMSET_CONTACT_SUCCESS = 'DELETE_CONFIRMSET_CONTACT_SUCCESS';
export const DELETE_CONFIRMSET_CONTACT_FAILURE = 'DELETE_CONFIRMSET_CONTACT_FAILURE';
