export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const CREATE_COMPANY = 'CREATE_COMPANY';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const CREATE_COMPANY_FAILURE = 'CREATE_COMPANY_FAILURE';

export const FILTERED_COMPANIES = 'FILTERED_COMPANIES';
export const FILTERED_COMPANIES_SUCCESS = 'FILTERED_COMPANIES_SUCCESS';
export const FILTERED_COMPANIES_FAILURE = 'FILTERED_COMPANIES_FAILURE';

export const FILTERED_INPUT = 'FILTERED_INPUT';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
