image: node:10.15.3
pipelines:
  default:
    - step:
        name: Unit Test 
        script:
          - npm install
          - npm run lint
          - npm run test
  branches:
    master:
      - step:
          name: Unit/E2E Test
          script:
            - npm install
            - npm run lint
            - npm run test 
            - npm run test:e2e